apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:                       # top-level spec
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:                  # template under top-level spec
    metadata:
      labels:
        app: nginx
    spec:                    # spec INSIDE template
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
